### ISSUE TITLE
Improvements to the theme

### ISSUE THREAD

**Issue by r0x0d** [XXXMrG/archie-zola#3]
Hi! 

I have done some improvements (IMHO) to theme to suite some of my use case, which mainly consist of translations -- not only for the posts, but the website in general  -- and some bugfixes with the footnotes when making references in the markdown. 

I don't know if you plan to keep updating this theme and introduce new things, but let me know if you would like me to open a PR with the changes I just mentioned.

Here's the my fork with all the changes: https://github.com/r0x0d/archie-zola

And if you want to check them out live, here's my blog that is using the latest changes from the fork: https://r0x0d.github.io 

Also, I have to mention that I'm fairly new to Zola and customizing themes, so probably some of the changes I made could be done in a simpler way 😅.

Thanks, and feel free to close this if you feel the changes in my fork will not suite this theme.

**Comment by XXXMrG** [comment]
Hi!, @r0x0d 
Sorry to reply so late!

I'm so glad to see you have a plan to contribute this theme. Of course, any PR would be welcome!

You can create a PR at any time, and I will review it as soon as possible.

I'm also a totally rookie to Zola, so we can discuss every problem you found, You can remind me at any time in case my response is not timely.

Thanks!

**Comment by XXXMrG** [comment]
Hi！ @r0x0d 
I have reviewed your fork. That looks good to me and have been merged.
Thanks for your contribution!

**Comment by r0x0d** [comment]
Hey, @XXXMrG! Thanks for that. 

Sorry for not opening the pull request earlier, I was so busy with work that I completely forgot this issue. I'm glad you were able to merge things from my fork. 

If I find something else that I can improve to your theme, I will definitely do that.

Once again, sorry for not opening the PR, and thanks for taking care of it!
